export const WORDS = [
  {
    id: "advise",
    word: "advise",
    chinese: "建議；勸告",
    partOfSpeech: "verb",
    sentence: "LeBron James can advise a rookie before the game.",
    sentenceZh: "LeBron James 可以在比賽前給一位新秀建議。",
    options: ["建議；勸告", "宣傳", "裝置", "修訂"],
    confusions: ["advertise＝宣傳", "device＝裝置", "revise＝修訂"],
  },
  {
    id: "affect",
    word: "affect",
    chinese: "影響",
    partOfSpeech: "verb",
    sentence: "A loud crowd can affect Stephen Curry's focus.",
    sentenceZh: "吵雜的觀眾可能影響 Stephen Curry 的專注力。",
    options: ["影響", "效果", "感染", "努力"],
    confusions: ["effect＝效果", "infect＝感染", "effort＝努力"],
  },
  {
    id: "afraid",
    word: "afraid",
    chinese: "害怕的",
    partOfSpeech: "adjective",
    sentence: "Anthony Edwards is not afraid to take the final shot.",
    sentenceZh: "Anthony Edwards 不害怕投出最後一球。",
    options: ["害怕的", "避免", "大聲地", "單獨的"],
    confusions: ["avoid＝避免", "aloud＝大聲地", "alone＝單獨的"],
  },
  {
    id: "afternoon",
    word: "afternoon",
    chinese: "下午",
    partOfSpeech: "noun",
    sentence: "Victor Wembanyama practices in the afternoon.",
    sentenceZh: "Victor Wembanyama 在下午練球。",
    options: ["下午", "之後", "後來", "中午"],
    confusions: ["after＝之後", "afterward＝後來", "noon＝中午"],
  },
  {
    id: "after",
    word: "after",
    chinese: "在……之後",
    partOfSpeech: "preposition",
    sentence: "Luka Doncic stretches after the game.",
    sentenceZh: "Luka Doncic 在比賽後伸展。",
    options: ["在……之後", "在……之前", "稍後", "再一次"],
    confusions: ["before＝在……之前", "later＝稍後", "again＝再一次"],
  },
  {
    id: "against",
    word: "against",
    chinese: "對抗；反對",
    partOfSpeech: "preposition",
    sentence: "Nikola Jokic plays against a strong defender.",
    sentenceZh: "Nikola Jokic 對抗一位強壯的防守球員。",
    options: ["對抗；反對", "再一次", "在……之中", "在兩者之間"],
    confusions: ["again＝再一次", "among＝在……之中", "between＝在兩者之間"],
  },
  {
    id: "again",
    word: "again",
    chinese: "再一次",
    partOfSpeech: "adverb",
    sentence: "Stephen Curry shoots again after missing once.",
    sentenceZh: "Stephen Curry 投失一次後再次出手。",
    options: ["再一次", "對抗；反對", "以前", "離開"],
    confusions: ["against＝對抗", "ago＝以前", "away＝離開"],
  },
  {
    id: "age",
    word: "age",
    chinese: "年齡",
    partOfSpeech: "noun",
    sentence: "Age does not stop LeBron James from training hard.",
    sentenceZh: "年齡不會阻止 LeBron James 努力訓練。",
    options: ["年齡", "以前", "代理人", "頁面"],
    confusions: ["ago＝以前", "agent＝代理人", "page＝頁面"],
  },
  {
    id: "ago",
    word: "ago",
    chinese: "以前",
    partOfSpeech: "adverb",
    sentence: "The coach called Jayson Tatum a minute ago.",
    sentenceZh: "教練一分鐘前叫了 Jayson Tatum。",
    options: ["以前", "年齡", "再一次", "離開"],
    confusions: ["age＝年齡", "again＝再一次", "away＝離開"],
  },
  {
    id: "agree",
    word: "agree",
    chinese: "同意",
    partOfSpeech: "verb",
    sentence: "Jayson Tatum and his coach agree on the final play.",
    sentenceZh: "Jayson Tatum 和教練同意最後一波戰術。",
    options: ["同意", "生氣的", "問候", "爭論"],
    confusions: ["angry＝生氣的", "greet＝問候", "argue＝爭論"],
  },
  {
    id: "ahead",
    word: "ahead",
    chinese: "在前面；向前",
    partOfSpeech: "adverb",
    sentence: "Stephen Curry runs ahead of his defender.",
    sentenceZh: "Stephen Curry 跑在防守球員前面。",
    options: ["在前面；向前", "頭", "聽見", "害怕的"],
    confusions: ["head＝頭", "hear＝聽見", "afraid＝害怕的"],
  },
  {
    id: "aim",
    word: "aim",
    chinese: "瞄準；目標",
    partOfSpeech: "verb / noun",
    sentence: "Kevin Durant takes aim at the basket.",
    sentenceZh: "Kevin Durant 瞄準籃框。",
    options: ["瞄準；目標", "手臂", "空氣；空中", "警報"],
    confusions: ["arm＝手臂", "air＝空氣", "alarm＝警報"],
  },
  {
    id: "air-conditioner",
    word: "air conditioner",
    chinese: "冷氣機",
    partOfSpeech: "noun",
    sentence: "The air conditioner keeps the locker room cool for LeBron James.",
    sentenceZh: "冷氣機讓 LeBron James 使用的休息室保持涼爽。",
    options: ["冷氣機", "航空公司", "飛機", "機場"],
    confusions: ["airlines＝航空公司", "airplane＝飛機", "airport＝機場"],
  },
  {
    id: "airlines",
    word: "airlines",
    chinese: "航空公司",
    partOfSpeech: "noun",
    sentence: "Some airlines fly NBA teams across the country.",
    sentenceZh: "有些航空公司載著 NBA 球隊飛越全國。",
    options: ["航空公司", "冷氣機", "飛機", "機場"],
    confusions: ["air conditioner＝冷氣機", "airplane＝飛機", "airport＝機場"],
  },
  {
    id: "airplane",
    word: "airplane",
    chinese: "飛機",
    partOfSpeech: "noun",
    sentence: "Luka Doncic rests on the airplane before an away game.",
    sentenceZh: "Luka Doncic 在客場比賽前於飛機上休息。",
    options: ["飛機", "航空公司", "冷氣機", "機場"],
    confusions: ["airlines＝航空公司", "air conditioner＝冷氣機", "airport＝機場"],
  },
  {
    id: "airport",
    word: "airport",
    chinese: "機場",
    partOfSpeech: "noun",
    sentence: "Jayson Tatum meets his teammates at the airport.",
    sentenceZh: "Jayson Tatum 在機場與隊友會合。",
    options: ["機場", "飛機", "航空公司", "冷氣機"],
    confusions: ["airplane＝飛機", "airlines＝航空公司", "air conditioner＝冷氣機"],
  },
  {
    id: "air",
    word: "air",
    chinese: "空氣；空中",
    partOfSpeech: "noun",
    sentence: "Victor Wembanyama jumps high into the air for a dunk.",
    sentenceZh: "Victor Wembanyama 高高躍向空中灌籃。",
    options: ["空氣；空中", "頭髮", "耳朵", "手臂"],
    confusions: ["hair＝頭髮", "ear＝耳朵", "arm＝手臂"],
  },
  {
    id: "alarm-clock",
    word: "alarm clock",
    chinese: "鬧鐘",
    partOfSpeech: "noun",
    sentence: "Stephen Curry's alarm clock rings before morning practice.",
    sentenceZh: "Stephen Curry 的鬧鐘在晨間練習前響起。",
    options: ["鬧鐘", "警報", "時鐘", "相簿；專輯"],
    confusions: ["alarm＝警報", "clock＝時鐘", "album＝相簿"],
  },
  {
    id: "alarm",
    word: "alarm",
    chinese: "警報",
    partOfSpeech: "noun",
    sentence: "LeBron James hears the arena alarm during a safety drill.",
    sentenceZh: "LeBron James 在安全演練時聽見球場警報。",
    options: ["警報", "鬧鐘", "手臂", "相簿；專輯"],
    confusions: ["alarm clock＝鬧鐘", "arm＝手臂", "album＝相簿"],
  },
  {
    id: "album",
    word: "album",
    chinese: "相簿；專輯",
    partOfSpeech: "noun",
    sentence: "Anthony Edwards keeps a photo album from his basketball season.",
    sentenceZh: "Anthony Edwards 保存一本記錄籃球賽季的相簿。",
    options: ["相簿；專輯", "警報", "飛機", "瞄準；目標"],
    confusions: ["alarm＝警報", "airplane＝飛機", "aim＝目標"],
  },
];
