export const WORDS = [
  {
    id: "advise",
    word: "advise",
    chinese: "建議；勸告",
    partOfSpeech: "verb",
    sentence: "LeBron James can advise a rookie before the game.",
    sentenceZh: "LeBron James 可以在比賽前給一位新秀建議。",
    options: ["建議；勸告", "宣傳", "裝置", "修訂"],
    confusions: ["advertise＝宣傳", "device＝裝置", "revise＝修訂"],
  },
  {
    id: "affect",
    word: "affect",
    chinese: "影響",
    partOfSpeech: "verb",
    sentence: "A loud crowd can affect Stephen Curry's focus.",
    sentenceZh: "吵雜的觀眾可能影響 Stephen Curry 的專注力。",
    options: ["影響", "效果", "感染", "努力"],
    confusions: ["effect＝效果", "infect＝感染", "effort＝努力"],
  },
  {
    id: "afraid",
    word: "afraid",
    chinese: "害怕的",
    partOfSpeech: "adjective",
    sentence: "Anthony Edwards is not afraid to take the final shot.",
    sentenceZh: "Anthony Edwards 不害怕投出最後一球。",
    options: ["害怕的", "避免", "大聲地", "單獨的"],
    confusions: ["avoid＝避免", "aloud＝大聲地", "alone＝單獨的"],
  },
  {
    id: "afternoon",
    word: "afternoon",
    chinese: "下午",
    partOfSpeech: "noun",
    sentence: "Victor Wembanyama practices in the afternoon.",
    sentenceZh: "Victor Wembanyama 在下午練球。",
    options: ["下午", "之後", "後來", "中午"],
    confusions: ["after＝之後", "afterward＝後來", "noon＝中午"],
  },
  {
    id: "after",
    word: "after",
    chinese: "在……之後",
    partOfSpeech: "preposition",
    sentence: "Luka Doncic stretches after the game.",
    sentenceZh: "Luka Doncic 在比賽後伸展。",
    options: ["在……之後", "在……之前", "稍後", "再一次"],
    confusions: ["before＝在……之前", "later＝稍後", "again＝再一次"],
  },
  {
    id: "against",
    word: "against",
    chinese: "對抗；反對",
    partOfSpeech: "preposition",
    sentence: "Nikola Jokic plays against a strong defender.",
    sentenceZh: "Nikola Jokic 對抗一位強壯的防守球員。",
    options: ["對抗；反對", "再一次", "在……之中", "在兩者之間"],
    confusions: ["again＝再一次", "among＝在……之中", "between＝在兩者之間"],
  },
  {
    id: "again",
    word: "again",
    chinese: "再一次",
    partOfSpeech: "adverb",
    sentence: "Stephen Curry shoots again after missing once.",
    sentenceZh: "Stephen Curry 投失一次後再次出手。",
    options: ["再一次", "對抗；反對", "以前", "離開"],
    confusions: ["against＝對抗", "ago＝以前", "away＝離開"],
  },
  {
    id: "age",
    word: "age",
    chinese: "年齡",
    partOfSpeech: "noun",
    sentence: "Age does not stop LeBron James from training hard.",
    sentenceZh: "年齡不會阻止 LeBron James 努力訓練。",
    options: ["年齡", "以前", "代理人", "頁面"],
    confusions: ["ago＝以前", "agent＝代理人", "page＝頁面"],
  },
  {
    id: "ago",
    word: "ago",
    chinese: "以前",
    partOfSpeech: "adverb",
    sentence: "The coach called Jayson Tatum a minute ago.",
    sentenceZh: "教練一分鐘前叫了 Jayson Tatum。",
    options: ["以前", "年齡", "再一次", "離開"],
    confusions: ["age＝年齡", "again＝再一次", "away＝離開"],
  },
  {
    id: "agree",
    word: "agree",
    chinese: "同意",
    partOfSpeech: "verb",
    sentence: "Jayson Tatum and his coach agree on the final play.",
    sentenceZh: "Jayson Tatum 和教練同意最後一波戰術。",
    options: ["同意", "生氣的", "問候", "爭論"],
    confusions: ["angry＝生氣的", "greet＝問候", "argue＝爭論"],
  },
  {
    id: "ahead",
    word: "ahead",
    chinese: "在前面；向前",
    partOfSpeech: "adverb",
    sentence: "Stephen Curry runs ahead of his defender.",
    sentenceZh: "Stephen Curry 跑在防守球員前面。",
    options: ["在前面；向前", "頭", "聽見", "害怕的"],
    confusions: ["head＝頭", "hear＝聽見", "afraid＝害怕的"],
  },
  {
    id: "aim",
    word: "aim",
    chinese: "瞄準；目標",
    partOfSpeech: "verb / noun",
    sentence: "Kevin Durant takes aim at the basket.",
    sentenceZh: "Kevin Durant 瞄準籃框。",
    options: ["瞄準；目標", "手臂", "空氣；空中", "警報"],
    confusions: ["arm＝手臂", "air＝空氣", "alarm＝警報"],
  },
  {
    id: "air-conditioner",
    word: "air conditioner",
    chinese: "冷氣機",
    partOfSpeech: "noun",
    sentence: "The air conditioner keeps the locker room cool for LeBron James.",
    sentenceZh: "冷氣機讓 LeBron James 使用的休息室保持涼爽。",
    options: ["冷氣機", "航空公司", "飛機", "機場"],
    confusions: ["airlines＝航空公司", "airplane＝飛機", "airport＝機場"],
  },
  {
    id: "airlines",
    word: "airlines",
    chinese: "航空公司",
    partOfSpeech: "noun",
    sentence: "Some airlines fly NBA teams across the country.",
    sentenceZh: "有些航空公司載著 NBA 球隊飛越全國。",
    options: ["航空公司", "冷氣機", "飛機", "機場"],
    confusions: ["air conditioner＝冷氣機", "airplane＝飛機", "airport＝機場"],
  },
  {
    id: "airplane",
    word: "airplane",
    chinese: "飛機",
    partOfSpeech: "noun",
    sentence: "Luka Doncic rests on the airplane before an away game.",
    sentenceZh: "Luka Doncic 在客場比賽前於飛機上休息。",
    options: ["飛機", "航空公司", "冷氣機", "機場"],
    confusions: ["airlines＝航空公司", "air conditioner＝冷氣機", "airport＝機場"],
  },
  {
    id: "airport",
    word: "airport",
    chinese: "機場",
    partOfSpeech: "noun",
    sentence: "Jayson Tatum meets his teammates at the airport.",
    sentenceZh: "Jayson Tatum 在機場與隊友會合。",
    options: ["機場", "飛機", "航空公司", "冷氣機"],
    confusions: ["airplane＝飛機", "airlines＝航空公司", "air conditioner＝冷氣機"],
  },
  {
    id: "air",
    word: "air",
    chinese: "空氣；空中",
    partOfSpeech: "noun",
    sentence: "Victor Wembanyama jumps high into the air for a dunk.",
    sentenceZh: "Victor Wembanyama 高高躍向空中灌籃。",
    options: ["空氣；空中", "頭髮", "耳朵", "手臂"],
    confusions: ["hair＝頭髮", "ear＝耳朵", "arm＝手臂"],
  },
  {
    id: "alarm-clock",
    word: "alarm clock",
    chinese: "鬧鐘",
    partOfSpeech: "noun",
    sentence: "Stephen Curry's alarm clock rings before morning practice.",
    sentenceZh: "Stephen Curry 的鬧鐘在晨間練習前響起。",
    options: ["鬧鐘", "警報", "時鐘", "相簿；專輯"],
    confusions: ["alarm＝警報", "clock＝時鐘", "album＝相簿"],
  },
  {
    id: "alarm",
    word: "alarm",
    chinese: "警報",
    partOfSpeech: "noun",
    sentence: "LeBron James hears the arena alarm during a safety drill.",
    sentenceZh: "LeBron James 在安全演練時聽見球場警報。",
    options: ["警報", "鬧鐘", "手臂", "相簿；專輯"],
    confusions: ["alarm clock＝鬧鐘", "arm＝手臂", "album＝相簿"],
  },
  {
    id: "album",
    word: "album",
    chinese: "相簿；專輯",
    partOfSpeech: "noun",
    sentence: "Anthony Edwards keeps a photo album from his basketball season.",
    sentenceZh: "Anthony Edwards 保存一本記錄籃球賽季的相簿。",
    options: ["相簿；專輯", "警報", "飛機", "瞄準；目標"],
    confusions: ["alarm＝警報", "airplane＝飛機", "aim＝目標"],
  },
  {
    id: "award",
    word: "award",
    chinese: "獎項；授予",
    partOfSpeech: "noun / verb",
    sentence: "Nikola Jokic receives an award after an excellent season.",
    sentenceZh: "Nikola Jokic 在一個出色的賽季後獲得獎項。",
    options: ["獎項；授予", "知道的", "在交通工具上", "在前面；向前"],
    confusions: ["aware＝知道的", "aboard＝在交通工具上", "ahead＝在前面"],
  },
  {
    id: "anime",
    word: "anime",
    chinese: "日本動畫",
    partOfSpeech: "noun",
    sentence: "Anthony Edwards sees an anime poster in the arena shop.",
    sentenceZh: "Anthony Edwards 在球館商店看到一張日本動畫海報。",
    options: ["日本動畫", "動物", "相簿；專輯", "文章"],
    confusions: ["animal＝動物", "album＝相簿", "article＝文章"],
  },
  {
    id: "article",
    word: "article",
    chinese: "文章",
    partOfSpeech: "noun",
    sentence: "Jayson Tatum reads an article about strong defense.",
    sentenceZh: "Jayson Tatum 閱讀一篇關於強力防守的文章。",
    options: ["文章", "藝術家", "行動；動作", "活躍的；積極的"],
    confusions: ["artist＝藝術家", "action＝行動", "active＝活躍的"],
  },
  {
    id: "angle",
    word: "angle",
    chinese: "角度",
    partOfSpeech: "noun",
    sentence: "Stephen Curry changes the angle of his bank shot.",
    sentenceZh: "Stephen Curry 改變擦板投籃的角度。",
    options: ["角度", "天使", "腳踝", "相簿；專輯"],
    confusions: ["angel＝天使", "ankle＝腳踝", "album＝相簿"],
  },
  {
    id: "air-purifier",
    word: "air purifier",
    chinese: "空氣清淨機",
    partOfSpeech: "noun",
    sentence: "An air purifier keeps LeBron James's locker room fresh.",
    sentenceZh: "空氣清淨機讓 LeBron James 的休息室保持空氣清新。",
    options: ["空氣清淨機", "冷氣機", "機場", "飛機"],
    confusions: ["air conditioner＝冷氣機", "airport＝機場", "airplane＝飛機"],
  },
  {
    id: "a-few",
    word: "a few",
    chinese: "一些；幾個（可數）",
    partOfSpeech: "determiner",
    sentence: "LeBron James makes a few passes before taking the shot.",
    sentenceZh: "LeBron James 在出手前傳了幾次球。",
    options: ["一些；幾個（可數）", "一點；少量（不可數）", "很多；非常", "幾乎沒有（可數）"],
    confusions: ["a little＝一點（不可數）", "a lot＝很多", "few＝幾乎沒有（可數）"],
  },
  {
    id: "a-little",
    word: "a little",
    chinese: "一點；少量（不可數）",
    partOfSpeech: "determiner",
    sentence: "Kevin Durant drinks a little water during the timeout.",
    sentenceZh: "Kevin Durant 在暫停期間喝了一點水。",
    options: ["一點；少量（不可數）", "一些；幾個（可數）", "很多；非常", "幾乎沒有（不可數）"],
    confusions: ["a few＝一些（可數）", "a lot＝很多", "little＝幾乎沒有（不可數）"],
  },
  {
    id: "a-lot",
    word: "a lot",
    chinese: "很多；非常",
    partOfSpeech: "adverb phrase",
    sentence: "Luka Doncic practices a lot before an important game.",
    sentenceZh: "Luka Doncic 在重要比賽前做大量練習。",
    options: ["很多；非常", "一點；少量（不可數）", "一些；幾個（可數）", "分配"],
    confusions: ["a little＝一點", "a few＝一些", "allot＝分配"],
  },
  {
    id: "a-m",
    word: "a.m.",
    chinese: "上午",
    partOfSpeech: "abbreviation",
    sentence: "Victor Wembanyama arrives at 8 a.m. for practice.",
    sentenceZh: "Victor Wembanyama 上午八點抵達球館練習。",
    options: ["上午", "下午；晚上", "瞄準；目標", "數量"],
    confusions: ["p.m.＝下午／晚上", "aim＝瞄準", "amount＝數量"],
  },
  {
    id: "able",
    word: "able",
    chinese: "能夠的；有能力的",
    partOfSpeech: "adjective",
    sentence: "Stephen Curry is able to shoot from far behind the line.",
    sentenceZh: "Stephen Curry 能夠從三分線外很遠的地方投籃。",
    options: ["能夠的；有能力的", "不能的", "能力", "關於；大約"],
    confusions: ["unable＝不能的", "ability＝能力", "about＝關於"],
  },
  {
    id: "about",
    word: "about",
    chinese: "關於；大約",
    partOfSpeech: "preposition / adverb",
    sentence: "The coach talks with LeBron James about the next play.",
    sentenceZh: "教練和 LeBron James 討論下一個戰術。",
    options: ["關於；大約", "在……上方；超過", "在國外；到國外", "在周圍"],
    confusions: ["above＝在上方", "abroad＝在國外", "around＝在周圍"],
  },
  {
    id: "above",
    word: "above",
    chinese: "在……上方；超過",
    partOfSpeech: "preposition / adverb",
    sentence: "Victor Wembanyama holds the ball above the defender.",
    sentenceZh: "Victor Wembanyama 把球舉在防守球員上方。",
    options: ["在……上方；超過", "關於；大約", "在……下方", "在國外；到國外"],
    confusions: ["about＝關於", "below＝在下方", "abroad＝在國外"],
  },
  {
    id: "abroad",
    word: "abroad",
    chinese: "在國外；到國外",
    partOfSpeech: "adverb",
    sentence: "Giannis Antetokounmpo travels abroad for an NBA preseason game.",
    sentenceZh: "Giannis Antetokounmpo 為了 NBA 季前賽前往國外。",
    options: ["在國外；到國外", "在交通工具上", "在……上方；超過", "在周圍"],
    confusions: ["aboard＝在交通工具上", "above＝在上方", "around＝在周圍"],
  },
  {
    id: "absent",
    word: "absent",
    chinese: "缺席的；不在的",
    partOfSpeech: "adjective",
    sentence: "LeBron James asks why a rookie is absent from practice.",
    sentenceZh: "LeBron James 詢問一位新秀為什麼缺席練習。",
    options: ["缺席的；不在的", "出席的；現在的", "意外；事故", "在國外；到國外"],
    confusions: ["present＝出席的", "accident＝意外", "abroad＝在國外"],
  },
  {
    id: "accept",
    word: "accept",
    chinese: "接受",
    partOfSpeech: "verb",
    sentence: "Jayson Tatum accepts the coach's advice before the game.",
    sentenceZh: "Jayson Tatum 在賽前接受教練的建議。",
    options: ["接受", "除了", "期待", "使用權；進入"],
    confusions: ["except＝除了", "expect＝期待", "access＝使用權／進入"],
  },
  {
    id: "accident",
    word: "accident",
    chinese: "意外；事故",
    partOfSpeech: "noun",
    sentence: "An accident on the road delays the NBA team bus.",
    sentenceZh: "路上的一場事故耽誤了 NBA 球隊巴士。",
    options: ["意外；事故", "事件", "缺席的；不在的", "帳戶"],
    confusions: ["incident＝事件", "absent＝缺席的", "account＝帳戶"],
  },
  {
    id: "across",
    word: "across",
    chinese: "穿過；在……對面",
    partOfSpeech: "preposition / adverb",
    sentence: "Stephen Curry passes the ball across the court to a teammate.",
    sentenceZh: "Stephen Curry 把球橫傳過球場給隊友。",
    options: ["穿過；在……對面", "在周圍", "在國外；到國外", "在……上方；超過"],
    confusions: ["around＝在周圍", "abroad＝在國外", "above＝在上方"],
  },
  {
    id: "action",
    word: "action",
    chinese: "行動；動作",
    partOfSpeech: "noun",
    sentence: "Anthony Edwards joins the action near the basket.",
    sentenceZh: "Anthony Edwards 加入籃框附近的攻防行動。",
    options: ["行動；動作", "活躍的；積極的", "演員", "文章"],
    confusions: ["active＝活躍的", "actor＝演員", "article＝文章"],
  },
  {
    id: "active",
    word: "active",
    chinese: "活躍的；積極的",
    partOfSpeech: "adjective",
    sentence: "Jayson Tatum stays active on defense all game.",
    sentenceZh: "Jayson Tatum 整場比賽在防守端都保持積極。",
    options: ["活躍的；積極的", "行動；動作", "演員", "活動"],
    confusions: ["action＝行動", "actor＝演員", "activity＝活動"],
  },
];
